server:
  port: 8080
  servlet:
    context-path: /user
spring:
  application:
    name: user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootvue?characterEncoding=UTF-8
    username: root
    password: root
mybatis:
  mapper-locations: classpath:com/lzx/mapper/*.xml
  type-aliases-package: com.lzx.vue.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
